  version: '3.9'

  services:
    db:
      image: postgres:13.3
      env_file: DatingSite/.env
      volumes:
        - postgres_data:/var/lib/postgresql/data/
    web:
      build:
        context: .
      command: >
        sh -c "python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
      ports:
        - "8000:8000"
      env_file: DatingSite/.env
      volumes:
        - .:/usr/src/app
      depends_on:
        - db

  volumes:
    static_volume:
    postgres_data:

