# Generated by Django 4.1.6 on 2023-02-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="country_of_residence",
            field=models.CharField(default="not specified", max_length=100),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("different", "Different"),
                    ("not_specified", "Not Specified"),
                ],
                default="not_specified",
                max_length=20,
            ),
        ),
    ]
