# Generated by Django 4.1.6 on 2023-03-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0003_alter_userinfo_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="liked_users",
            field=models.ManyToManyField(to="user_profile.userinfo"),
        ),
    ]
